name: Calculate Build Version

on:
  workflow_call:
    outputs:
      version:
        description: "New build version number"
        value: ${{ jobs.calculate_version.outputs.output1 }}

jobs:
  calculate_version:
    name: Calculate Build Version
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.versionStep.outputs.version}}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Download version file from cache
      uses: actions/cache@v3
      env:
        cache-name: build-version-cache
      with:
        path: ./buildVersion.txt
        key: buildVersion
    - name: Increment build version
      id: versionStep
      shell: bash
      run: |
        [ -f buildVersion.txt ] && valu=`cat buildVersion.txt` || value="2.0.0-build1"
        buildVersionNumber=$((${value##*build} + 1))
        newVersionNumber="${value%%build*}build${buildVersionNumber}"
        expr $newVersionNumber > buildVersion.txt
        echo "::set-output name=version::${newVersionNumber}"
