name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Add package source
      run: dotnet nuget add source --username Smrecz --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/TATUM"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack Tatum.CSharp.Core
      run: dotnet pack ./Tatum.CSharp.Core/Tatum.CSharp.Core.csproj --no-build --no-restore --configuration Release /p:Version=2.0.0.0 --output .
    - name: Push to Github Packages
      run: dotnet nuget push "./Tatum.CSharp.Core.2.0.0.nupkg"  --api-key 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 --source "github"
