name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Core_Pack_RC:
    uses: ./.github/workflows/prepareBuildPackage.yml
    with:
      name: Core
      version: 2.0.0
    secrets: inherit
  
  ETH_Pack_RC:
    uses: ./.github/workflows/prepareBuildPackage.yml
    with:
      name: Ethereum
      version: 2.0.0
    secrets: inherit
    needs: Core_Pack_RC
    
  ETH_Integration_Tests:
    uses: ./.github/workflows/prepareBuildPackage.yml
    with:
      name: Ethereum
    secrets: inherit
    needs: ETH_Pack_RC